---
# The list of environments managed by helmfile.
#
# The default is `environments: {"default": {}}` which implies:
#
# - `{{ .Environment.Name }}` evaluates to "default"
# - `{{ .Values }}` being empty
environments:
  home:
    kubeContext: k3s
  civo: {}
  gcp: {}
  kind: {}
