apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "google-dynamic-dns-update.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "google-dynamic-dns-update.name" . }}
    helm.sh/chart: {{ include "google-dynamic-dns-update.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  dns.sh: |
    #!/bin/sh
    set -e
    {{- range .Values.dns }}
    /usr/bin/curl  -v -XPOST https://{{ .auth }}@domains.google.com/nic/update?hostname={{ .host }}
    {{- end }}